@extends('layouts.profile')
@section('banner', asset('images/101755206_p0_master1200.jpg'))
@section('pfp', asset($viewData['avatar']))
@section('username', $viewData['username'])
@section('pronouns', $viewData['pronouns'])
@section('description', $viewData['bio'])
